version: '3'

services:
  db:
    image: z10g/b17r:v1
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/b17r
    ports:
      - "8000:8000"
    depends_on:
      - db
